### ISSUE TITLE
Segfault when dist.all_reduce(torch.ones(2, device=torch.device("cuda", rank)) on DGX-1

### ISSUE THREAD

**Issue by froody** [openucx/torch-ucc#14] opened 2020-09-23 23:09 UTC
Code to repro: https://gist.github.com/froody/c9e6749e877e0f0edfe412d079d73719
Command to repro: `TORCH_UCC_COLL_BACKEND=xccl python bug.py`
Output: https://gist.github.com/froody/f1c8107f7bd1a1650cdd47d64406a7d5

pytorch: 1.6.0
torch-ucc: a277d7da24ae6e8a40bda658d0f0d4e06fcadb8b (master)
ucx: 1.9.0
cuda: 10.1

**Comment by froody** [comment] 2020-09-23 23:45
Similar crash when running the included allreduce test:

`TORCH_UCC_COLL_BACKEND=xccl ./start_test.sh torch_allreduce_test.py --backend=ucc --use-cuda`

**Comment by froody** [comment] 2020-09-24 00:18
Oh, I was missing WITH_CUDA= when building, I feel like this should raise an exception early on instead of failing in this fashion

**Comment by Sergei-Lebedev** [comment] 2020-09-24 09:35
Currently there is no way to determine if XCCL supports cuda buffers at compile time or runtime because cuda component is loadable module and even if it's present it doesn't mean it will be loaded. We can address this issue in UCC when will move XCCL code into it.

**Comment by jladd-mlnx** [comment] 2020-10-14 20:08
@froody - we discussed this one over with @srinivas212 on Friday, and all agree this is the expected behavior. Closing as we won't change this.

**Closed as completed by jladd-mlnx** 2020-10-14 20:08 UTC
